---
title: "Homework 8: Spatial Visualization"
author: "Meghan Devlin"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
library(sf)
library(ggplot2)
library(tidycensus)
library(ggmap)
library(osmdata)
library(leaflet)
library(RColorBrewer)
library(rprojroot)


##API code from drivetimes:
api_key <- Sys.getenv("MAPS_API_KEY")

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = FALSE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


```{r data_read, include = FALSE}

library(ggthemes, quietly = TRUE)

mn.df <-
  st_read("./data/USA_Counties/USA_Counties.shp", quiet = TRUE) %>%
  janitor::clean_names() %>%
  filter(state_name %in% "Minnesota")



#Get the bounding box and county outline
mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
as_tibble() %>%
  rename(longitude = V1, latitude = V2)


#Get map from ggmap
#Get the base map (foundational layer)
mn_base.map <- get_map(
  location = mn.box,
  source   = "stamen",
  maptype  = "terrain",
  crop = TRUE
)

#Create the base map
hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )


coord_ggmap <- st_crs(hennepin_base.gg) #NA


osm_shop_sf.df <- opq(bbox = "minnesota") %>%
  add_osm_feature(key = "shop", value = c("watches", "travel_agency", "toys")) %>%
  osmdata_sf()
#Extract the relevent sf data frame
shop_points.df <- osm_shop_sf.df$osm_points %>% 
  janitor::clean_names() %>%
  filter(!is.na(shop)) %>% #only retain 'valid' tags
  dplyr::select(osm_id, name, shop, opening_hours, phone, website, geometry) %>%
  mutate(shop = str_to_title(shop) %>% as_factor())


#Let's add it to a hennepin_base.gg
hennepin_base.gg +
  geom_sf(data = shop_points.df,
          aes(colour = shop),
          inherit.aes = FALSE,
          alpha = 0.8, shape = 16) +
  labs(title = "Hennepin County, MN OSM Features") + 
  scale_colour_viridis_d("Store") +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

#Call viridis library  
library(viridis, quietly = TRUE)

#Extract the levels/order of shop type factor
shop_types <- levels(shop_points.df$shop)
n_types    <- length(shop_types)

#Initialize our colour pallete (discrete in this case)
my_pallete <- colorFactor(viridis_pal(option = "D")(n_types), levels = shop_types)

#Call our leaflet
leaflet(data = shop_points.df) %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(shop),
    opacity = 0.4,
    weight  = 2, #outline strength
    radius  = 4 #size of circle
  ) %>%
  addLegend(
    title    = "Store Type",
    position = "bottomright",
    colors   = viridis_pal(option = "D")(n_types),
    labels   = shop_types 
  )

#Need html tools to get our labels to render appropriately
library(htmltools, quietly = TRUE)

#Add a text label like normal
shop_label.df <- shop_points.df %>%
  mutate(
    across(
      c(name, opening_hours:website),
      ~ifelse(is.na(.x), "NA", .x)
    ),
    text_label = str_c(
      name,
      "<br/>Store Type: ",
      shop,
      "<br/>Open Hours: ",
      opening_hours,
      "<br/>Phone: ",
      phone,
      "<br/>Website: ",
      website
    )
  )

##Chart B

library(tidycensus)


census_api_key("4e91e26c6ae56e6e6d8f0e17e072db2ef08c8f2b", overwrite = TRUE)



mn_under25.df <- get_acs(
  geography = "tract",
  variables = "B19037_002E", #Code for Estimate Total Householder under 25 years
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE,
  cb        = FALSE
) 

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - Locations of Travel Agencies, Watch Stores and Toy Stores in Minnesota (and in the WI, SD, ND near the Minnesota border)

```{r}

### Chart B - Estimated Householders in Hennepin County under the age 25 years

#Plot normally
under25.gg <- ggplot() + 
  geom_sf(data = mn_under25.df, aes(fill = estimate)) + 
  labs(title = "Hennepin County, MN 2020 ACS Estimated Householder \nunder 25 Years Old") + 
  theme_void() + 
  scale_fill_viridis_c("Under 25 Years", labels = scales::comma)

#Display
under25.gg
```


